#!/usr/bin/python3

#This is logrunner, which displays a feed of new entries appended to a log file.
#Handy for watching apache or nginx access/error logs.
#Chris Mailloux

import argparse,time,atexit,os,datetime

parser = argparse.ArgumentParser(description = "Displays a feed of updates appended to the log file of your choosing")
parser.add_argument(dest = "path", help = "Path of file to run")
parser.add_argument("-r", "--refresh", dest = "refresh", default = 1, type = float, help = "Refresh speed in seconds (default: 1)")
parser.add_argument("-t", "--timestamp", dest = "timestamp", default = False, action = 'store_true', help = "Adds a timestamp to each update")
args = parser.parse_args()

def exit_handler():
  log_file.close()
  print("Exit!")

atexit.register(exit_handler)

print("\nLog Runner Initialized ->",args.path,"\n")

log_file = open(args.path,"rb")
pos = log_file.tell()
fileinfo = os.stat(args.path)
filesize = fileinfo.st_size

while True:
  fileinfo = os.stat(args.path)
  if fileinfo.st_size > filesize:
    log_file.seek(filesize,0)
    if(args.timestamp == False):
      print(log_file.read().decode("utf-8"),end='')
    else:
      print("[",'{:%Y-%b-%d %H:%M:%S}'.format(datetime.datetime.now()),"]",log_file.read().decode("utf-8"),end='')
    filesize = fileinfo.st_size
  time.sleep(args.refresh)


